spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DATABASE:journaldb}
      auto-index-creation: true

server:
  port: ${PORT:8080}
  servlet:
    context-path: /journal

weather:
  api:
    key: ${WEATHER_API_KEY}